/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.simulatorxcsa;

import java.awt.Color;
import java.io.FileNotFoundException;
import java.util.Arrays;
import java.util.Queue;
import java.util.LinkedList;

/**
 *
 * @author sagar
 */
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
    }
/*Initializing objects of classes to use their functions when a button is clicked*/
    Init initobj=new Init();
    GetMAR getmarobj=new GetMAR();
    SetMAR setmarobj=new SetMAR();
    RunInstruction runinstructionobj=new RunInstruction();
    Cache cacheobj=new Cache();
    RunProgram1 rp1=new RunProgram1();
    RunProgram2 rp2=new RunProgram2();
    
/*initializing values of each bit of U/I*/    
        String x0 ="0";
	String x1 ="0";
	String x2 ="0";
	String x3 ="0";
	String x4 ="0";
	String x5 ="0";
	String x6 ="0";
	String x7 ="0";
	String x8 ="0";
	String x9 ="0";
	String x10="0";
	String x11="0";
	String x12="0";
	String x13="0";
	String x14="0";
	String x15="0";

/*Defining memory array*/
        
        int [] memory= new int[4095];

/*Defining Condition Code Register*/

    int [] CCR= new int[]{0,0,0,0,0};

    String [] csh=new String[16];
    int csh_count=0;
/*defining gloabal vaiables to understand which program is being run*/ 
    
    int prgm;
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GPR0 = new java.awt.TextField();
        button1 = new java.awt.Button();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        GPR1 = new java.awt.TextField();
        button2 = new java.awt.Button();
        jLabel2 = new javax.swing.JLabel();
        GPR2 = new java.awt.TextField();
        button3 = new java.awt.Button();
        jLabel3 = new javax.swing.JLabel();
        GPR3 = new java.awt.TextField();
        button4 = new java.awt.Button();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        IXR1 = new java.awt.TextField();
        button5 = new java.awt.Button();
        jLabel6 = new javax.swing.JLabel();
        IXR2 = new java.awt.TextField();
        button6 = new java.awt.Button();
        IXR3 = new java.awt.TextField();
        button7 = new java.awt.Button();
        jLabel7 = new javax.swing.JLabel();
        PC = new java.awt.TextField();
        button8 = new java.awt.Button();
        jLabel8 = new javax.swing.JLabel();
        MAR = new java.awt.TextField();
        button9 = new java.awt.Button();
        jLabel9 = new javax.swing.JLabel();
        MBR = new java.awt.TextField();
        button10 = new java.awt.Button();
        jLabel10 = new javax.swing.JLabel();
        IR = new java.awt.TextField();
        jLabel11 = new javax.swing.JLabel();
        MFR = new java.awt.TextField();
        jLabel12 = new javax.swing.JLabel();
        textField13 = new java.awt.TextField();
        Priviledged = new javax.swing.JLabel();
        Init = new javax.swing.JButton();
        Load = new javax.swing.JButton();
        Store = new javax.swing.JButton();
        Run = new javax.swing.JButton();
        SS = new javax.swing.JButton();
        HALT = new javax.swing.JLabel();
        RUN = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Program1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cache = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        FEC = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        Reset = new javax.swing.JButton();
        keyboard = new java.awt.TextField();
        Program2 = new javax.swing.JButton();
        console_printer = new java.awt.TextArea();
        jLabel17 = new javax.swing.JLabel();
        FR0 = new java.awt.TextField();
        button11 = new java.awt.Button();
        FR1 = new java.awt.TextField();
        button12 = new java.awt.Button();
        jLabel18 = new javax.swing.JLabel();
        FADD = new javax.swing.JButton();
        VADD = new javax.swing.JButton();
        CNVRT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GPR0.setEditable(false);
        GPR0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPR0ActionPerformed(evt);
            }
        });

        button1.setActionCommand("LD");
        button1.setLabel("LD");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        jToggleButton1.setText("15");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("14");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jToggleButton3.setText("13");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jToggleButton4.setText("12");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        jToggleButton5.setText("11");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });

        jToggleButton6.setText("10");
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });

        jToggleButton7.setText("9");
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });

        jToggleButton8.setText("8");
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });

        jToggleButton9.setText("7");
        jToggleButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton9ActionPerformed(evt);
            }
        });

        jToggleButton10.setText("6");
        jToggleButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton10ActionPerformed(evt);
            }
        });

        jToggleButton11.setText("5");
        jToggleButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton11ActionPerformed(evt);
            }
        });

        jToggleButton12.setText("4");
        jToggleButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton12ActionPerformed(evt);
            }
        });

        jToggleButton13.setText("3");
        jToggleButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton13ActionPerformed(evt);
            }
        });

        jToggleButton14.setText("2");
        jToggleButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton14ActionPerformed(evt);
            }
        });

        jToggleButton15.setText("1");
        jToggleButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton15ActionPerformed(evt);
            }
        });

        jToggleButton16.setText("0");
        jToggleButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton16ActionPerformed(evt);
            }
        });

        jLabel1.setText("GPR 0");

        GPR1.setEditable(false);
        GPR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPR1ActionPerformed(evt);
            }
        });

        button2.setActionCommand("LD");
        button2.setLabel("LD");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        jLabel2.setText("GPR 1");

        GPR2.setEditable(false);
        GPR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPR2ActionPerformed(evt);
            }
        });

        button3.setActionCommand("LD");
        button3.setLabel("LD");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        jLabel3.setText("GPR 3");

        GPR3.setEditable(false);
        GPR3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPR3ActionPerformed(evt);
            }
        });

        button4.setActionCommand("LD");
        button4.setLabel("LD");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        jLabel4.setText("GPR 2");

        jLabel5.setText("IXR 1");

        IXR1.setEditable(false);
        IXR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IXR1ActionPerformed(evt);
            }
        });

        button5.setActionCommand("LD");
        button5.setLabel("LD");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });

        jLabel6.setText("IXR 2");

        IXR2.setEditable(false);
        IXR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IXR2ActionPerformed(evt);
            }
        });

        button6.setActionCommand("LD");
        button6.setLabel("LD");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });

        IXR3.setEditable(false);
        IXR3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IXR3ActionPerformed(evt);
            }
        });

        button7.setActionCommand("LD");
        button7.setLabel("LD");
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });

        jLabel7.setText("IXR 3");

        PC.setEditable(false);
        PC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PCActionPerformed(evt);
            }
        });

        button8.setActionCommand("LD");
        button8.setLabel("LD");
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });

        jLabel8.setText("PC");

        MAR.setEditable(false);
        MAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MARActionPerformed(evt);
            }
        });

        button9.setActionCommand("LD");
        button9.setLabel("LD");
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });

        jLabel9.setText("MAR");

        MBR.setEditable(false);
        MBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MBRActionPerformed(evt);
            }
        });

        button10.setActionCommand("LD");
        button10.setLabel("LD");
        button10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button10ActionPerformed(evt);
            }
        });

        jLabel10.setText("MBR");

        IR.setEditable(false);
        IR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IRActionPerformed(evt);
            }
        });

        jLabel11.setText("IR");

        MFR.setEditable(false);
        MFR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MFRActionPerformed(evt);
            }
        });

        jLabel12.setText("MFR");

        textField13.setEditable(false);
        textField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField13ActionPerformed(evt);
            }
        });

        Priviledged.setText("Priviledged");

        Init.setText("init");
        Init.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InitActionPerformed(evt);
            }
        });

        Load.setText("Load");
        Load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadActionPerformed(evt);
            }
        });

        Store.setText("Store");
        Store.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StoreActionPerformed(evt);
            }
        });

        Run.setText("Run");
        Run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunActionPerformed(evt);
            }
        });

        SS.setText("SS");
        SS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SSActionPerformed(evt);
            }
        });

        HALT.setText("HALT");

        RUN.setText("RUN");

        jLabel13.setText("Keyboard");

        jLabel14.setText("Console Printer");

        jLabel15.setText("Cache");

        Program1.setText("Program 1");
        Program1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Program1ActionPerformed(evt);
            }
        });

        cache.setEditable(false);
        cache.setColumns(20);
        cache.setRows(5);
        jScrollPane1.setViewportView(cache);

        FEC.setEditable(false);
        FEC.setColumns(20);
        FEC.setRows(5);
        jScrollPane2.setViewportView(FEC);

        jLabel16.setText("Field Engineers Console");

        Reset.setText("Reset All");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        Program2.setText("Program 2");
        Program2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Program2ActionPerformed(evt);
            }
        });

        console_printer.setEditable(false);

        jLabel17.setText("FR 0");

        FR0.setEditable(false);
        FR0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FR0ActionPerformed(evt);
            }
        });

        button11.setActionCommand("LD");
        button11.setLabel("LD");
        button11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button11ActionPerformed(evt);
            }
        });

        FR1.setEditable(false);
        FR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FR1ActionPerformed(evt);
            }
        });

        button12.setActionCommand("LD");
        button12.setLabel("LD");
        button12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button12ActionPerformed(evt);
            }
        });

        jLabel18.setText("FR 1");

        FADD.setText("FADD Example");
        FADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FADDActionPerformed(evt);
            }
        });

        VADD.setText("VADD Example");
        VADD.setActionCommand("VADD Example");
        VADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VADDActionPerformed(evt);
            }
        });

        CNVRT.setText("CNVRT Example");
        CNVRT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CNVRTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CNVRT)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GPR2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(GPR1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(GPR0, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(IXR1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(GPR3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IXR2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel18))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(FR0, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(button11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(FR1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(button12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(IXR3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MBR, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IR, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MFR, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PC, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MAR, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Priviledged)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textField13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel13)
                                    .addComponent(keyboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel14))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(console_printer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(618, 618, 618)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Store, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Reset)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Program2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Program1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(Load, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(SS, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Run, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                            .addComponent(Init, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(FADD)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(VADD)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jToggleButton2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jToggleButton4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jToggleButton7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jToggleButton8)
                                        .addGap(10, 10, 10)
                                        .addComponent(jToggleButton9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jToggleButton10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jToggleButton11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jToggleButton12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jToggleButton13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jToggleButton14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jToggleButton15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jToggleButton16)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HALT)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(RUN)))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel8)
                            .addComponent(button8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(MAR, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel10)
                                            .addComponent(MBR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(IR, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(MFR, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textField13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Priviledged))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(HALT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RUN))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Init)
                                    .addComponent(Load)
                                    .addComponent(Store))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Run)
                                    .addComponent(SS)
                                    .addComponent(Program1)
                                    .addComponent(Reset)
                                    .addComponent(Program2)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(GPR0, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(button2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(4, 4, 4))
                            .addComponent(GPR1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(GPR2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3)
                            .addComponent(button4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GPR3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5)
                            .addComponent(button5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IXR1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6)
                            .addComponent(button6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IXR2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7)
                            .addComponent(button7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IXR3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(button11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FR0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(button12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FR1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton2)
                    .addComponent(jToggleButton3)
                    .addComponent(jToggleButton4)
                    .addComponent(jToggleButton5)
                    .addComponent(jToggleButton6)
                    .addComponent(jToggleButton7)
                    .addComponent(jToggleButton8)
                    .addComponent(jToggleButton9)
                    .addComponent(jToggleButton10)
                    .addComponent(jToggleButton11)
                    .addComponent(jToggleButton12)
                    .addComponent(jToggleButton13)
                    .addComponent(jToggleButton14)
                    .addComponent(jToggleButton15)
                    .addComponent(jToggleButton16)
                    .addComponent(FADD)
                    .addComponent(VADD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CNVRT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(keyboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(console_printer, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                .addContainerGap())
        );

        GPR0.getAccessibleContext().setAccessibleName("");
        VADD.getAccessibleContext().setAccessibleName("VADD Example");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GPR0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPR0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GPR0ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
    
        GPR0.setText(getValue());
    }//GEN-LAST:event_button1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if (jToggleButton1.isSelected())
        {
            x15="1";
            jToggleButton1.setForeground(Color.red);
        }
        else
        {
            x15="0";
            jToggleButton1.setForeground(Color.black);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        if (jToggleButton2.isSelected())
        {
            x14="1";
            jToggleButton2.setForeground(Color.red);
        }
        else
        {
            x14="0";
            jToggleButton2.setForeground(Color.black);
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        if (jToggleButton3.isSelected())
        {
            x13="1";
            jToggleButton3.setForeground(Color.red);
        }
        else
        {
            x13="0";
            jToggleButton3.setForeground(Color.black);
        }
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        if (jToggleButton4.isSelected())
        {
            x12="1";
            jToggleButton4.setForeground(Color.red);
        }
        else
        {
            x12="0";
            jToggleButton4.setForeground(Color.black);
        }
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        if (jToggleButton5.isSelected())
        {
            x11="1";
            jToggleButton5.setForeground(Color.red);
        }
        else
        {
            x11="0";
            jToggleButton5.setForeground(Color.black);
        }
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        if (jToggleButton6.isSelected())
        {
            x10="1";
            jToggleButton6.setForeground(Color.red);
        }
        else
        {
            x10="0";
            jToggleButton6.setForeground(Color.black);
        }
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
        if (jToggleButton7.isSelected())
        {
            x9="1";
            jToggleButton7.setForeground(Color.red);
        }
        else
        {
            x9="0";
            jToggleButton7.setForeground(Color.black);
        }
    }//GEN-LAST:event_jToggleButton7ActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
        if (jToggleButton8.isSelected())
        {
            x8="1";
            jToggleButton8.setForeground(Color.red);
        }
        else
        {
            x8="0";
            jToggleButton8.setForeground(Color.black);
        }
    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void jToggleButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton9ActionPerformed
        if (jToggleButton9.isSelected())
        {
            x7="1";
            jToggleButton9.setForeground(Color.red);
        }
        else
        {
            x7="0";
            jToggleButton9.setForeground(Color.black);
        }
    }//GEN-LAST:event_jToggleButton9ActionPerformed

    private void jToggleButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton10ActionPerformed
        if (jToggleButton10.isSelected())
        {
            x6="1";
            jToggleButton10.setForeground(Color.red);
        }
        else
        {
            x6="0";
            jToggleButton10.setForeground(Color.black);
        }
    }//GEN-LAST:event_jToggleButton10ActionPerformed

    private void jToggleButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton11ActionPerformed
        if (jToggleButton11.isSelected())
        {
            x5="1";
            jToggleButton11.setForeground(Color.red);
        }
        else
        {
            x5="0";
            jToggleButton11.setForeground(Color.black);
        }
    }//GEN-LAST:event_jToggleButton11ActionPerformed

    private void jToggleButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton12ActionPerformed
        if (jToggleButton12.isSelected())
        {
            x4="1";
            jToggleButton12.setForeground(Color.red);
        }
        else
        {
            x4="0";
            jToggleButton12.setForeground(Color.black);
        }
    }//GEN-LAST:event_jToggleButton12ActionPerformed

    private void jToggleButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton13ActionPerformed
        if (jToggleButton13.isSelected())
        {
            x3="1";
            jToggleButton13.setForeground(Color.red);
        }
        else
        {
            x3="0";
            jToggleButton13.setForeground(Color.black);
        }
    }//GEN-LAST:event_jToggleButton13ActionPerformed

    private void jToggleButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton14ActionPerformed
        if (jToggleButton14.isSelected())
        {
            x2="1";
            jToggleButton14.setForeground(Color.red);
        }
        else
        {
            x2="0";
            jToggleButton14.setForeground(Color.black);
        }
    }//GEN-LAST:event_jToggleButton14ActionPerformed

    private void jToggleButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton15ActionPerformed
        if (jToggleButton15.isSelected())
        {
            x1="1";
            jToggleButton15.setForeground(Color.red);
        }
        else
        {
            x1="0";
            jToggleButton15.setForeground(Color.black);
        }
    }//GEN-LAST:event_jToggleButton15ActionPerformed

    private void jToggleButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton16ActionPerformed
        if (jToggleButton16.isSelected())
        {
            x0="1";
            jToggleButton16.setForeground(Color.red);
        }
        else
        {
            x0="0";
            jToggleButton16.setForeground(Color.black);
        }
    }//GEN-LAST:event_jToggleButton16ActionPerformed

    private void GPR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GPR1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        GPR1.setText(getValue());
    }//GEN-LAST:event_button2ActionPerformed

    private void GPR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPR2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GPR2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        GPR2.setText(getValue());
    }//GEN-LAST:event_button3ActionPerformed

    private void GPR3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPR3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GPR3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        GPR3.setText(getValue());
    }//GEN-LAST:event_button4ActionPerformed

    private void IXR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IXR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IXR1ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        IXR1.setText(getValue());
    }//GEN-LAST:event_button5ActionPerformed

    private void IXR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IXR2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IXR2ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        IXR2.setText(getValue());
    }//GEN-LAST:event_button6ActionPerformed

    private void IXR3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IXR3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IXR3ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        IXR3.setText(getValue());
    }//GEN-LAST:event_button7ActionPerformed

    private void PCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PCActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        String t=getValue();
        t=t.substring(4, 16);
        
        PC.setText(t);
    }//GEN-LAST:event_button8ActionPerformed

    private void MARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MARActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        String t=getValue();
        t=t.substring(4, 16);
        MAR.setText(t);
    }//GEN-LAST:event_button9ActionPerformed

    private void MBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MBRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MBRActionPerformed

    private void button10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button10ActionPerformed
        MBR.setText(getValue());
    }//GEN-LAST:event_button10ActionPerformed

    private void IRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IRActionPerformed

    private void MFRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MFRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MFRActionPerformed

    private void textField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField13ActionPerformed

/*Below Button will read the input file and initialize its values into the memory and 
    Set the PC to 0
    IR1-IR3 to 0
    GPR0-GPR3 to 0
    */
    private void InitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InitActionPerformed
        try
        {
            memory=initobj.readfile();
            GPR0.setText("0000000000000000");
            GPR1.setText("0000000000000000");
            GPR2.setText("0000000000000000");
            GPR3.setText("0000000000000000");
            IXR1.setText("0000000000000000");
            IXR2.setText("0000000000000000");
            IXR3.setText("0000000000000000");
            IR.setText("");
            PC.setText("000000000000");
            MAR.setText("");
            MBR.setText("");
            prgm=0;
        }
        catch (Exception e) {
            System.out.println("An error occurred.");
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_InitActionPerformed
/*Below Button action will Load the value of the Address of MAR into MBR*/
    private void LoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadActionPerformed
        String MAR=this.MAR.getText();
        if (!MAR.isEmpty())
        {
        String mbr=getmarobj.GetMARValue(memory, MAR);
        MBR.setText(mbr);
        String Console="Instruction Load: At Memory:";
        Console=Console+MAR+" Value:"+mbr+"\n";
        System.out.println(Console);
        this.appendTextArea(this.FEC, Console);
        cacheobj.PrintCache(this, MAR, mbr);
        }
    }//GEN-LAST:event_LoadActionPerformed
/*Below Button Action take the Value of MAR and Value of MBR and set the Value of MBR in the Memory at address MAR
    If either are empty it will do nothing*/
    private void StoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StoreActionPerformed
        String mar=this.MAR.getText();
        String mbr=MBR.getText();
        if (!mar.isEmpty() && !mbr.isEmpty())
        {
            memory=setmarobj.SetMAR(this,memory, mar, mbr);
            String Console="Instruction Store: At Memory:";
            Console=Console+mar+" Value:"+mbr+"\n";
            System.out.println(Console);
            this.appendTextArea(this.FEC, Console);
            cacheobj.PrintCache(this, mar, mbr);
        } 
    }//GEN-LAST:event_StoreActionPerformed

/*this buuton action will execute the instructions from PC address till halt Memcode is received */
    private void RunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunActionPerformed
        String pc=PC.getText();
        String ixr1=IXR1.getText();
        String ixr2=IXR2.getText();
        String ixr3=IXR3.getText();
        runinstructionobj.Run(this, memory, pc, ixr1, ixr2, ixr3);
    }//GEN-LAST:event_RunActionPerformed

/*this button will instructions from PC and increment PC*/    
    private void SSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SSActionPerformed
//        runinstructionobj.SStemp(this);
        String pc=PC.getText();
        String ixr1=IXR1.getText();
        String ixr2=IXR2.getText();
        String ixr3=IXR3.getText();
        runinstructionobj.SS(this, memory, pc, ixr1, ixr2, ixr3);
    }//GEN-LAST:event_SSActionPerformed

/*Below button action will Load Program 1 into the memory and take the input from the simulator
    It will then set PC to start of the program*/    
    private void Program1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Program1ActionPerformed
        try
        {
            memory=rp1.readfile();
            GPR0.setText("0000000000000000");
            GPR1.setText("0000000000000000");
            GPR2.setText("0000000000000000");
            GPR3.setText("0000000000000000");
            IXR1.setText("0000000000000000");
            IXR2.setText("0000000000000000");
            IXR3.setText("0000000000000000");
            IR.setText("");
            PC.setText("000000000000");
            MAR.setText("");
            MBR.setText("");
            rp1.readKeyboard(this);
            PC.setText("000000100000");
            prgm=1;
        }
        catch (Exception e) {
            System.out.println("An error occurred.");
            e.printStackTrace();
        }        
    }//GEN-LAST:event_Program1ActionPerformed
/*Below button will reset the simulator and set all register values to 0*/
    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        Arrays.fill(memory, 0);
        GPR0.setText("0000000000000000");
        GPR1.setText("0000000000000000");
        GPR2.setText("0000000000000000");
        GPR3.setText("0000000000000000");
        IXR1.setText("0000000000000000");
        IXR2.setText("0000000000000000");
        IXR3.setText("0000000000000000");
        FR0.setText("0000000000000000");
        FR1.setText("0000000000000000");
        IR.setText("");
        PC.setText("000000000000");
        MAR.setText("");
        MBR.setText("");
        this.SetLabelColorB(HALT);
        this.setTextArea(FEC, "");
        this.setTextArea(cache, "");
        this.setTextField(keyboard, "");
        this.setTextAreaT(console_printer, "");
        csh_count=0;
        this.setTextField(MFR, "0000");
        
    }//GEN-LAST:event_ResetActionPerformed

    private void Program2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Program2ActionPerformed
        try
        {
            memory=rp2.readfile();
            rp2.readsSntences(this);
            GPR0.setText("0000000000000000");
            GPR1.setText("0000000000000000");
            GPR2.setText("0000000000000000");
            GPR3.setText("0000000000000000");
            IXR1.setText("0000000000000000");
            IXR2.setText("0000000000000000");
            IXR3.setText("0000000000000000");
            IR.setText("");
            PC.setText("000000000000");
            MAR.setText("");
            MBR.setText("");
            PC.setText("000001010000");
            prgm=2;
            
        }
        catch (Exception e) {
            System.out.println("An error occurred.");
            e.printStackTrace();
        } 
    }//GEN-LAST:event_Program2ActionPerformed

    private void FR0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FR0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FR0ActionPerformed

    private void button11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button11ActionPerformed
        FR0.setText(getValue());
    }//GEN-LAST:event_button11ActionPerformed

    private void FR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FR1ActionPerformed

    private void button12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button12ActionPerformed
        FR1.setText(getValue());
    }//GEN-LAST:event_button12ActionPerformed

    private void FADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FADDActionPerformed
        // TODO add your handling code here:
        Arrays.fill(memory, 0);
        GPR0.setText("0000000000000000");
        GPR1.setText("0000000000000000");
        GPR2.setText("0000000000000000");
        GPR3.setText("0000000000000000");
        IXR1.setText("0000000000000000");
        IXR2.setText("0000000000000000");
        IXR3.setText("0000000000000000");
        FR0.setText("0000000000000000");
        FR1.setText("0000000000000000");
        IR.setText("");
        PC.setText("000000000000");
        MAR.setText("");
        MBR.setText("");
        this.SetLabelColorB(HALT);
        this.setTextArea(FEC, "");
        this.setTextArea(cache, "");
        this.setTextField(keyboard, "");
        this.setTextAreaT(console_printer, "");
        csh_count=0;
        this.setTextField(MFR, "0000");
        
        memory[7]=8;        
        String Console="Instruction Store: At Memory:";
        String mar="000000000111";
        String mbr="0000000000001000";
        Console=Console+mar+" Value:"+mbr+"\n";
        this.appendTextArea(this.FEC, Console);
        cacheobj.PrintCache(this, mar, mbr);
        
        memory[32]=27655;
        Console="Instruction Store: At Memory:";
        mar="000000100000";
        mbr="0110110000000111";
        Console=Console+mar+" Value:"+mbr+"\n";
        this.appendTextArea(this.FEC, Console);
        cacheobj.PrintCache(this, mar, mbr);
        PC.setText("000000100000");
            
    }//GEN-LAST:event_FADDActionPerformed

    private void VADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VADDActionPerformed
        // TODO add your handling code here:
        Arrays.fill(memory, 0);
        GPR0.setText("0000000000000000");
        GPR1.setText("0000000000000000");
        GPR2.setText("0000000000000000");
        GPR3.setText("0000000000000000");
        IXR1.setText("0000000000000000");
        IXR2.setText("0000000000000000");
        IXR3.setText("0000000000000000");
        FR0.setText("0000000000000000");
        FR1.setText("0000000000000000");
        IR.setText("");
        PC.setText("000000000000");
        MAR.setText("");
        MBR.setText("");
        this.SetLabelColorB(HALT);
        this.setTextArea(FEC, "");
        this.setTextArea(cache, "");
        this.setTextField(keyboard, "");
        this.setTextAreaT(console_printer, "");
        csh_count=0;
        this.setTextField(MFR, "0000");
        
        memory[7]=20;        
        String Console="Instruction Store: At Memory:";
        String mar="000000000111";
        String mbr="0000000000010100";
        Console=Console+mar+" Value:"+mbr+"\n";
        this.appendTextArea(this.FEC, Console);
        cacheobj.PrintCache(this, mar, mbr);
        
        memory[8]=5;
        Console="Instruction Store: At Memory:";
        mar="000000001000";
        mbr="0000000000000101";
        Console=Console+mar+" Value:"+mbr+"\n";
        this.appendTextArea(this.FEC, Console);
        cacheobj.PrintCache(this, mar, mbr);
        
        memory[32]=30471;
        Console="Instruction Store: At Memory:";
        mar="000000100000";
        mbr="0111011100000111";
        Console=Console+mar+" Value:"+mbr+"\n";
        this.appendTextArea(this.FEC, Console);
        cacheobj.PrintCache(this, mar, mbr);
        
        PC.setText("000000100000");
        
    }//GEN-LAST:event_VADDActionPerformed

    private void CNVRTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNVRTActionPerformed
        // TODO add your handling code here:
                Arrays.fill(memory, 0);
        GPR0.setText("0000000000000000");
        GPR1.setText("0000000000000000");
        GPR2.setText("0000000000000000");
        GPR3.setText("0000000000000000");
        IXR1.setText("0000000000000000");
        IXR2.setText("0000000000000000");
        IXR3.setText("0000000000000000");
        FR0.setText("0000000000000000");
        FR1.setText("0000000000000000");
        IR.setText("");
        PC.setText("000000000000");
        MAR.setText("");
        MBR.setText("");
        this.SetLabelColorB(HALT);
        this.setTextArea(FEC, "");
        this.setTextArea(cache, "");
        this.setTextField(keyboard, "");
        this.setTextAreaT(console_printer, "");
        csh_count=0;
        this.setTextField(MFR, "0000");
        
        GPR0.setText("0000000000000001");
        memory[7]=31;        
        String Console="Instruction Store: At Memory:";
        String mar="000000000111";
        String mbr="0000000000011111";
        Console=Console+mar+" Value:"+mbr+"\n";
        this.appendTextArea(this.FEC, Console);
        cacheobj.PrintCache(this, mar, mbr);
        
        memory[32]=31751;        
        Console="Instruction Store: At Memory:";
        mar="000000100000";
        mbr="0111110000000111";
        Console=Console+mar+" Value:"+mbr+"\n";
        this.appendTextArea(this.FEC, Console);
        cacheobj.PrintCache(this, mar, mbr);
        
        PC.setText("000000100000");
        
    }//GEN-LAST:event_CNVRTActionPerformed
    private String getValue()
    {
        String value=x15+x14+x13+x12+x11+x10+x9+x8+x7+x6+x5+x4+x3+x2+x1+x0;
        
        return value;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CNVRT;
    private javax.swing.JButton FADD;
    public javax.swing.JTextArea FEC;
    public java.awt.TextField FR0;
    public java.awt.TextField FR1;
    public java.awt.TextField GPR0;
    public java.awt.TextField GPR1;
    public java.awt.TextField GPR2;
    public java.awt.TextField GPR3;
    public javax.swing.JLabel HALT;
    public java.awt.TextField IR;
    public java.awt.TextField IXR1;
    public java.awt.TextField IXR2;
    public java.awt.TextField IXR3;
    private javax.swing.JButton Init;
    private javax.swing.JButton Load;
    public java.awt.TextField MAR;
    private java.awt.TextField MBR;
    public java.awt.TextField MFR;
    public java.awt.TextField PC;
    private javax.swing.JLabel Priviledged;
    private javax.swing.JButton Program1;
    private javax.swing.JButton Program2;
    private javax.swing.JLabel RUN;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Run;
    private javax.swing.JButton SS;
    private javax.swing.JButton Store;
    private javax.swing.JButton VADD;
    private java.awt.Button button1;
    private java.awt.Button button10;
    private java.awt.Button button11;
    private java.awt.Button button12;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private java.awt.Button button5;
    private java.awt.Button button6;
    private java.awt.Button button7;
    private java.awt.Button button8;
    private java.awt.Button button9;
    public javax.swing.JTextArea cache;
    public java.awt.TextArea console_printer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    public java.awt.TextField keyboard;
    private java.awt.TextField textField13;
    // End of variables declaration//GEN-END:variables

    /*function to set value of registers from other class*/

    public void setTextAreaT(java.awt.TextArea TA, String value) 
    {
        TA.setText(value);
    }
    
    public String getTextAreaT(java.awt.TextArea TA) 
    {
        String val=TA.getText();
        return val;
    }
    
    public void setTextField(java.awt.TextField TF, String value) 
    {
        TF.setText(value);
    }
    
    /*function to set value cache*/
    
    public void setTextArea(javax.swing.JTextArea TA, String value) 
    {
        TA.setText(value);
    }
    
    public String getTextArea(javax.swing.JTextArea TA) 
    {
        String val=TA.getText();
        return val;
    }    
    
    public void appendTextArea(javax.swing.JTextArea TA, String value) 
    {
        TA.append(value);
    }
    
    /*function to get value of registers from other class*/
    
    public String getTextField(java.awt.TextField TF) 
    {
        String val=TF.getText();
        return val;
    }
    
    /*function to set value of HALT as red from other class*/
    
    public void SetLabelColorR(javax.swing.JLabel JL)
    {
        JL.setForeground(Color.red);
    }
    
     /*function to set value of HALT as black from other class*/
    public void SetLabelColorB(javax.swing.JLabel JL)
    {
        JL.setForeground(Color.black);
    }

}
